spring.application.name=demo
# 1. Thông tin kết nối MySQL
# Thay 'ten_database_cua_ban' bằng tên DB thực tế bạn tạo trong MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/quan_ly_phong_kham_nha_khoa?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
# Nếu MySQL của bạn có mật khẩu thì điền vào đây, không có thì để trống
spring.datasource.password=

# 2. Cấu hình Hibernate (ORM Core)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Hiển thị câu lệnh SQL thực tế chạy dưới background (rất tiện để debug)
spring.jpa.show-sql=true

# 3. QUAN TRỌNG: Cấu hình tự tạo bảng (Auto DDL - Giống như Migration)
# 'none': Tắt chế độ tự cập nhật cấu trúc database để tránh lỗi foreign key với MySQL.
spring.jpa.hibernate.ddl-auto=none
