# ==========================================
# CẤU HÌNH LOCAL DATABASE (XAMPP / MySQL)
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3307/quan_ly_phong_kham_nha_khoa?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
# Nếu XAMPP có mật khẩu thì điền vào đây, không thì để trống
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# 'update': Tự động tạo bảng (giống lệnh migrate của Laravel). Bạn có thể để 'update' để bạn bè pull về chạy được luôn.
spring.jpa.hibernate.ddl-auto=update
